// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redirect.proto

package grpc_redirect

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RedirectParams struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectParams) Reset()         { *m = RedirectParams{} }
func (m *RedirectParams) String() string { return proto.CompactTextString(m) }
func (*RedirectParams) ProtoMessage()    {}
func (*RedirectParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c17d4fc1876bf7a, []int{0}
}

func (m *RedirectParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectParams.Unmarshal(m, b)
}
func (m *RedirectParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectParams.Marshal(b, m, deterministic)
}
func (m *RedirectParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectParams.Merge(m, src)
}
func (m *RedirectParams) XXX_Size() int {
	return xxx_messageInfo_RedirectParams.Size(m)
}
func (m *RedirectParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectParams.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectParams proto.InternalMessageInfo

func (m *RedirectParams) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*RedirectParams)(nil), "github.tranduythanh.grpc_redirect.RedirectParams")
}

func init() { proto.RegisterFile("redirect.proto", fileDescriptor_7c17d4fc1876bf7a) }

var fileDescriptor_7c17d4fc1876bf7a = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xc9,
	0x2c, 0x4a, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x2b, 0x29, 0x4a, 0xcc, 0x4b, 0x29, 0xad, 0x2c, 0xc9, 0x48, 0xcc, 0xcb, 0xd0,
	0x4b, 0x2f, 0x2a, 0x48, 0x8e, 0x87, 0x29, 0x54, 0x52, 0xe2, 0xe2, 0x0b, 0x82, 0xb2, 0x03, 0x12,
	0x8b, 0x12, 0x73, 0x8b, 0x85, 0x04, 0xb8, 0x98, 0x4b, 0x8b, 0x72, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x40, 0x4c, 0x27, 0xfe, 0x28, 0x5e, 0x14, 0x4d, 0x49, 0x6c, 0x60, 0xe3, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x95, 0x45, 0xb2, 0xff, 0x70, 0x00, 0x00, 0x00,
}
